---

- name: create amtool config
  ansible.builtin.template:
    force: true
    src: alertmanager/amtool.yml.j2
    dest: "{{ alertmanager_amtool.config_dir }}/config.yml"
    owner: alertmanager
    group: "{{ alertmanager_system_group }}"
    mode: 0640

- name: create alertmanager.yml
  ansible.builtin.template:
    force: true
    src: alertmanager/alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: root
    group: "{{ alertmanager_system_group }}"
    mode: 0640
  register: alertmanger_config
  notify:
    - validate config

- name: restart alertmanager if needed
  ansible.builtin.meta: flush_handlers

...
