---

- name: detect binary file for alertmanager
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ alertmanager_local_tmp_directory }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}/alertmanager"
  register: stat_file_binary

- name: propagate files
  when:
    - stat_file_binary.stat.exists
  block:
    - name: propagate alertmanager binaries
      ansible.builtin.copy:
        src: "{{ alertmanager_local_tmp_directory }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}/{{ item }}"
        dest: "{{ alertmanager_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ alertmanager_system_user }}"
        group: "{{ alertmanager_system_group }}"
        remote_src: "{{ 'true' if alertmanager_direct_download else 'false' }}"
      loop:
        - alertmanager
        - amtool

- name: make files executable
  ansible.builtin.file:
    path: "{{ alertmanager_install_path }}/{{ item }}"
    mode: 0755
    owner: "{{ alertmanager_system_user }}"
    group: "{{ alertmanager_system_group }}"
  loop:
    - alertmanager
    - amtool

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/alertmanager.fact
    mode: 0755

- name: create link to binary
  ansible.builtin.file:
    src: "{{ alertmanager_install_path }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: true
    follow: false
  loop:
    - alertmanager
    - amtool
  notify:
    - restart alertmanager

- name: create alertmanager data directory
  ansible.builtin.file:
    path: "{{ alertmanager_data_dir }}"
    state: directory
    owner: "{{ alertmanager_system_user }}"
    group: "{{ alertmanager_system_group }}"
    mode: 0755

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create alertmanager run configuration
      ansible.builtin.template:
        src: "alertmanager.j2"
        dest: "{{ alertmanager_defaults_directory }}/alertmanager"
        force: true
        owner: root
        group: "{{ alertmanager_system_group }}"
        mode: 0640

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/alertmanager.service.j2"
        dest: "{{ systemd_lib_directory }}/alertmanager.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/alertmanager.j2"
        dest: "/etc/conf.d/alertmanager"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/alertmanager.j2"
        dest: "/etc/init.d/alertmanager"
        owner: root
        group: root
        mode: 0750

- name: create alertmanager configuration directory
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}"
    state: directory
    owner: root
    group: "{{ alertmanager_system_group }}"
    mode: 0770

- name: create amtool configuration directory
  ansible.builtin.file:
    path: "{{ alertmanager_amtool.config_dir }}"
    state: directory
    owner: root
    group: "{{ alertmanager_system_group }}"
    mode: 0770

- name: create alertmanager templates directory
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: directory
    owner: root
    group: "{{ alertmanager_system_group }}"
    mode: 0770
  loop: "{{ alertmanager_templates }}"
  loop_control:
    label: "{{ item | dirname }}"

- name: detect template files
  ansible.builtin.set_fact:
    alertmanager_templates_files: "{{ lookup('file_glob', 'files/**/*.tmpl', ignore_missing=True) }}"

- debug:
    msg: "{{ alertmanager_templates_files }}"

- name: copy alertmanager templates
  become: true
  copy:
    src: "{{ item }}"
    dest: "alertmanager_config_dir }}/templates/"
    owner: root
    group: "{{ alertmanager_system_group }}"
    mode: 0640
  with_fileglob: "{{ alertmanager_custom_templates_files }}"
  notify:
    - restart alertmanager
  when:
    - alertmanager_custom_templates_files is defined
    - alertmanager_custom_templates_files | length > 0

...
