---

- name: restart alertmanager
  become: true
  ansible.builtin.service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  become: true
  ansible.builtin.service:
    name: alertmanager
    state: reloaded

- name: validate config
  ansible.builtin.command: |
    /usr/bin/amtool \
      check-config \
      --verbose \
      {{ alertmanager_config_dir }}/alertmanager.yml
  notify:
    - restart alertmanager

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
